# TODO: re-enable Metric/AbcSize, Metrics/CyclomaticComplexity, and Metrics/PerceivedComplexity
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.0
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/**/*_spec.rb"
Metrics/ClassLength:
  Max: 300
Metrics/LineLength:
  Max: 280
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/PredicateName:
  Enabled: true
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/BlockDelimiters:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
Style/FrozenStringLiteralComment:
  # TODO: re-enable when RUBYOPT = --enable-frozen-string-literal freezes globally.
  Enabled: false